### ISSUE TITLE
Join game doesn't advance to the waiting module

### ISSUE THREAD

**Issue by anyaeats160carrots** [mikeyamadeo/catan-node-server#35]
The client throws an error about the game cookie on join game.
Error output:
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
    ...
    at client.network.ServerProxy.doPost(ServerProxy.java:134)
    at client.network.ServerProxy.joinGame(ServerProxy.java:340)
    at client.join.JoinGameController.joinGame(JoinGameController.java:232)
...

**Comment by anyaeats160carrots** [comment]
Fixed
